/**
 * Refresh fixtures from live upstream.
 *
 * Walks every `*.recipe.ts` under `src/external/`, hits the recipe's
 * declared upstream URL, applies the recipe's `postProcess` (defaults to
 * `stripVolatile`), and writes the result to the recipe's `target` file.
 *
 *   pnpm --filter @reissulla/test-fixtures refresh
 *   pnpm --filter @reissulla/test-fixtures refresh -- --provider=digitransit-routing
 *   pnpm --filter @reissulla/test-fixtures refresh -- --recipe=<recipe-relative-path>
 *
 * Recipes declare their required env vars (e.g. DIGITRANSIT_API_KEY) and
 * the script fails fast if any are missing. Secrets are loaded from the
 * repo-root `.env` — the same file the API itself reads.
 *
 * CI does not run this. Fixture freshness is dev-owned: when the existing
 * schema-drift job flags an OTP2 change, the runbook is "refresh as part
 * of the fix".
 */
import { readdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { config as dotenvConfig } from "dotenv";

import { stripVolatile, type StripPolicy } from "../src/strip.js";

interface Recipe {
  url: string;
  method?: "GET" | "POST";
  body?: unknown;
  headersFromEnv?: Record<string, string>;
  requires?: string[];
  /** Target file relative to the recipe file's directory. */
  target: string;
  postProcess?: (data: unknown, defaultStrip: typeof stripVolatile) => unknown;
}

interface LoadedRecipe {
  filePath: string;
  exportName: string;
  recipe: Recipe;
}

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..", "..");
const fixturesRoot = resolve(here, "..", "src", "external");

dotenvConfig({ path: resolve(repoRoot, ".env") });

function parseArgs(argv: string[]): { provider?: string; recipe?: string } {
  const out: { provider?: string; recipe?: string } = {};
  for (const arg of argv) {
    const m = arg.match(/^--(provider|recipe)=(.+)$/);
    if (m) out[m[1] as "provider" | "recipe"] = m[2];
  }
  return out;
}

async function findRecipeFiles(root: string): Promise<string[]> {
  const out: string[] = [];
  async function walk(dir: string): Promise<void> {
    const entries = await readdir(dir, { withFileTypes: true });
    for (const e of entries) {
      const full = join(dir, e.name);
      if (e.isDirectory()) await walk(full);
      else if (e.isFile() && e.name.endsWith(".recipe.ts")) out.push(full);
    }
  }
  if (!existsSync(root)) return out;
  await walk(root);
  return out;
}

async function loadRecipe(filePath: string): Promise<LoadedRecipe | null> {
  const mod = (await import(pathToFileURL(filePath).href)) as Record<
    string,
    unknown
  >;
  const recipe = mod.recipe as Recipe | undefined;
  if (!recipe) {
    console.warn(`[skip] ${filePath} — no exported \`recipe\``);
    return null;
  }
  return { filePath, exportName: "recipe", recipe };
}

function checkSecrets(recipe: Recipe): void {
  for (const name of recipe.requires ?? []) {
    if (!process.env[name]) {
      throw new Error(
        `Recipe needs env var ${name} but it is not set. Set it in .env at the repo root and retry.`,
      );
    }
  }
}

function applyHeaders(recipe: Recipe): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [header, envName] of Object.entries(recipe.headersFromEnv ?? {})) {
    const v = process.env[envName];
    if (v) out[header] = v;
  }
  if (recipe.body !== undefined && !out["Content-Type"]) {
    out["Content-Type"] = "application/json";
  }
  return out;
}

async function runRecipe(loaded: LoadedRecipe): Promise<void> {
  const { filePath, recipe } = loaded;
  checkSecrets(recipe);

  const init: RequestInit = {
    method: recipe.method ?? "GET",
    headers: applyHeaders(recipe),
  };
  if (recipe.body !== undefined) init.body = JSON.stringify(recipe.body);

  const res = await fetch(recipe.url, init);
  if (!res.ok) {
    throw new Error(
      `Upstream ${recipe.url} → HTTP ${res.status} ${res.statusText}`,
    );
  }
  const raw = (await res.json()) as unknown;
  const processed = recipe.postProcess
    ? recipe.postProcess(raw, stripVolatile)
    : stripVolatile(raw);

  const targetPath = resolve(dirname(filePath), recipe.target);
  const banner = `// AUTO-GENERATED by scripts/refresh.ts — do not edit by hand.\n// Source: ${relative(repoRoot, filePath).replace(/\\/g, "/")}\n`;
  const exportLine = `export const data = ${JSON.stringify(processed, null, 2)} as const;\n`;
  await writeFile(targetPath, banner + exportLine, "utf-8");
  console.log(`[ok] ${relative(repoRoot, targetPath).replace(/\\/g, "/")}`);
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  const files = await findRecipeFiles(fixturesRoot);

  if (files.length === 0) {
    console.log(
      "No *.recipe.ts files found. Add a recipe alongside a fixture to register it.",
    );
    return;
  }

  const filtered = files.filter((f) => {
    const rel = relative(fixturesRoot, f).replace(/\\/g, "/");
    if (args.recipe) return rel === args.recipe || f.endsWith(args.recipe);
    if (args.provider) return rel.startsWith(`${args.provider}/`);
    return true;
  });

  if (filtered.length === 0) {
    console.error(
      `No recipes matched filter (provider=${args.provider}, recipe=${args.recipe})`,
    );
    process.exit(1);
  }

  let failed = 0;
  for (const f of filtered) {
    try {
      const loaded = await loadRecipe(f);
      if (loaded) await runRecipe(loaded);
    } catch (err) {
      failed += 1;
      console.error(
        `[fail] ${relative(repoRoot, f)} — ${(err as Error).message}`,
      );
    }
  }

  if (failed > 0) {
    process.exit(1);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});

// Allow per-recipe StripPolicy import for editor IntelliSense.
export type { StripPolicy };
